### ISSUE TITLE
Validation is wrong

### ISSUE THREAD

**Issue by ultrox** [marvinhagemeister/miniban#1]
Even your test return false, to otherwise valid iban. I'm looking for light version of iban validator, can you maybe fix it :)

[runkit](https://npm.runkit.com/miniban)

```
var miniban = require("miniban")
var iban = miniban.isValidIBAN("AL47212110090000000235698741");  //false
```

**Comment by marvinhagemeister** [comment]
Thanks for spotting this issue. I'm happy to take on any PRs 🍀
